package assign6;
//class name ExceptionHandling
import java.util.Scanner;

public class ExceptionHandling {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        try {
        
            System.out.println("enter first number:");
            String input1 = scanner.nextLine();
            System.out.println("enter second number:");
            String input2 = scanner.nextLine();

            int num1 = Integer.parseInt(input1);
            int num2 = Integer.parseInt(input2);

            int result = num1 / num2;
            System.out.println("result of division: " + result);

           
            int[] arr = {10, 20, 30};
            System.out.println("accessing 4th element of the array: " + arr[3]);
        } 
        catch (ArithmeticException e) {
            System.out.println("error: division by zero is not allowed.");
        } 
        catch (NumberFormatException e) {
            System.out.println("error: enter valid integers.");
        } 
        catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("error: array index is out of bounds.");
        } 
        finally {
            System.out.println("program execution completed.");
            scanner.close();
        }
    }
}

